name: Sync Develop To Main
on:
  push:
    branches:
      - main
permissions:
  pull-requests: write
  contents: read

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4

      - name: Opening pull request
        id: pull
        uses: HXavS/sync-branches@1.5.1
        continue-on-error: true
        with:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          FROM_BRANCH: "main"
          TO_BRANCH: "develop"
          PULL_REQUEST_TITLE: "chore: sync {FROM_BRANCH} to {TO_BRANCH}"